package day08

import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test
import utils.readInputText

class Day08Test {
  private val part1 = Day08.Part1()
  private val part2 = Day08.Part2()

  @Test
  fun `part 1 example 1`() {
    val input =
      """
      |..........
      |..........
      |..........
      |....a.....
      |..........
      |.....a....
      |..........
      |..........
      |..........
      |..........
      """
        .trimMargin()

    part1.solve(input).shouldBe(2)
  }

  @Test
  fun `part 1 example 2`() {
    val input =
      """
      |..........
      |..........
      |..........
      |....a.....
      |........a.
      |.....a....
      |..........
      |..........
      |..........
      |..........
      """
        .trimMargin()

    part1.solve(input).shouldBe(4)
  }

  @Test
  fun `part 1 sample input`() {
    val input = readInputText("day08/day08-sample.txt")
    part1.solve(input).shouldBe(14)
  }

  @Test
  fun `part 1 input`() {
    val input = readInputText("day08/day08-input.txt")
    part1.solve(input).shouldBe(254)
  }

  @Test
  fun `part 2 example input`() {
    val input =
      """
      |T.........
      |...T......
      |.T........
      |..........
      |..........
      |..........
      |..........
      |..........
      |..........
      |..........
      """
        .trimMargin()
    part2.solve(input).shouldBe(9)
  }

  @Test
  fun `part 2 sample input`() {
    val input = readInputText("day08/day08-sample.txt")
    part2.solve(input).shouldBe(34)
  }

  @Test
  fun `part 2 input`() {
    val input = readInputText("day08/day08-input.txt")
    part2.solve(input).shouldBe(951)
  }
}
